config/routes.rb
Rails.application.routes.draw do
  resources :trackers do
    member do
            get :count
        end
    end
  devise_for :users

  root 'trackers#index'

end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
    belongs_to :user
    validates_length_of :Name, :minimum => 3, :maximum => 50, :allow_blank => false
    validates_length_of :description, :maximum => 150
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trackers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]
  before_action :require_permission, only: [:show, :edit]

  def count
    tracker = Tracker.find(params[:id])
    tracker.counter +=1
    tracker.date_check = Date.today
    tracker.save

    redirect_to root_path
  end

  def require_permission
    if current_user != Tracker.find(params[:id]).user
        redirect_to root_path
    end
  end

  # GET /trackers
  # GET /trackers.json
  def index
    @trackers = Tracker.where(user_id: current_user.id)
  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    @tracker = current_user.trackers.build
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = current_user.trackers.build(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to @tracker, notice: 'Tracker was successfully created.' }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to @tracker, notice: 'Tracker was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: 'Tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit(:Counter, :Name, :Schedule, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DailyTracker</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Daily Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to("Home", root_path, class: "btn btn-default", style: "color:white")%>
            </li>
          </ul>
            <% if user_signed_in? %>
          <li>
            <%= link_to('Edit registration', edit_user_registration_path, { :style=>'color:#FFFFFF;', :class => 'btn btn-primary' }) %>
          </li>
            <% else %>
          <li>
            <%= link_to('Register', new_user_registration_path, { :style=>'color:#FFFFFF;', :class => 'btn btn-success' })  %>
          </li>
            <% end %>
          <form class="form-inline mt-2 mt-md-0">
            <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, :style=>'color:#FFFFFF;', :class => 'btn btn-danger') %>        
            </li>
            <% else %>
            <li>
            <%= link_to('Login', new_user_session_path, { :style=>'color:#FFFFFF;', :class => 'btn btn-success' })  %>  
            </li>
            <% end %>
          </form>
        </div>
      </nav>
<div class="container" style="text-align:center">
    </br>
    </br>
    </br>
    </br>
    </br>
    <%= yield %>
<div>

</body>
</html>

app/views/trackers/_form.html.erb
<%= form_for(@tracker) do |f| %>
  <% if @tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
      <% @tracker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field(:Name, {:class => 'form-control'}) %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_field(:description, {:class => 'form-control'}) %>
  </div>
  <div class="actions">
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </div>
<% end %>

app/views/trackers/edit.html.erb
<h1>Editing habit</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracker, :class => 'btn btn-default' %> |
<%= link_to 'Back', trackers_path, :class => 'btn btn-default' %>

app/views/trackers/index.html.erb
<% if notice %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<h1>My habits</h1>

<table class="table">
  <thead>
    <tr>
      <th>Days done</th>
      <th>Name</th>
      <th>Created</th>
      <th>Last time done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.counter %> / <%= (Date.today.to_date - tracker.created_at.to_date).to_i + 1%></td>
        <td><%= tracker.Name %></td>
        <td><%= tracker.created_at.to_date %></td>
        <td><%= tracker.date_check %></td>
        <td style="text-align: right">
        <%= link_to 'Show', tracker, :class => 'btn btn-default' %>
        <%= link_to 'Edit', edit_tracker_path(tracker), :class => 'btn btn-default' %>
        <% if tracker.date_check != Date.today %>
            <%= link_to 'Done', count_tracker_path(tracker), { :style=>'color:#FFFFFF;', :class => 'btn btn-success' } %>
        <% end %>
        <%= link_to 'Delete', tracker, method: :delete, data: { confirm: 'Are you sure?' }, :style=>'color:#FFFFFF;', :class=>'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tracker', new_tracker_path, { :style=>'color:#FFFFFF;', :class => 'btn btn-primary' } %>

app/views/trackers/new.html.erb
<h1>New habit</h1>

<%= render 'form' %>

<%= link_to 'Back', trackers_path, :class => 'btn btn-default' %>

app/views/trackers/show.html.erb
<% if notice %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>
<div class="form-control">
<p>
  <strong>Days done:</strong>
  <%= @tracker.counter %> / <%= (Date.today.to_date - @tracker.created_at.to_date).to_i + 1 %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tracker.Name %>
</p>
<p>
  <strong>Created on:</strong>
  <%= @tracker.created_at %>
</p>

<p>
  <strong>Last time done:</strong>
  <%= @tracker.date_check %>
</p>
<p>
  <strong>Description:</strong>
  <%= @tracker.description %>
</p>
</div>

<%= link_to 'Edit', edit_tracker_path(@tracker), :class => 'btn btn-default' %> |
<%= link_to 'Back', trackers_path, :class => 'btn btn-default' %>